using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chacal.Chat.Interfaces
{
    public interface ILlmClient
    {
        /// <summary>
        /// Sends a message to the LLM and retrieves the generated response.
        /// </summary>
        /// <param name="message">User input message.</param>
        /// <returns>Response generated by the LLM.</returns>
        Task<string> SendMessageAsync(string message);
    }
}
